apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'otel-collector-metrics'
        static_configs:
          - targets: ['otel-collector:8889']
      - job_name: "prometheus"
        static_configs:
          - targets: ["192.168.159.136:9090"]
      - job_name: 'otel-health'
        static_configs:
          - targets: ['otel-collector:8888']  
      - job_name: " "
        metrics_path: /metrics
        static_configs:
          - targets: ["192.168.159.1:8000"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args: ["--config.file=/etc/prometheus/prometheus.yml"]
         # Limite de RAM pour tes 16Go
        resources:
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-vol
          mountPath: /etc/prometheus
        ports:
        - containerPort: 9090
      volumes:
      - name: config-vol
        configMap:
          name: prometheus-conf
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
  type: NodePort